export var AIM_TUNING = {
    STALE_MS: 1500,
    SHOOT_LAG_S: 0.025,
    BURST_LOCK_MS: 100,
    BURST_LOCK_MAX_DRIFT: 160,
    LOS_CACHE_TTL_MS: 100,
    LOS_CACHE_PURGE_MS: 500,
    DEFAULT_MOVE_SPEED: 720,
    STATIONARY_VEL_FLOOR: 30,
    STATIONARY_VEL_RATIO: 0.07,
    SCORE_DIST_WEIGHT: 1,
    SCORE_SPEED_WEIGHT: 0.3,
    SCORE_APPROACH_WEIGHT: 0.4,
    SCORE_FACING_WEIGHT: 0.5,
    TARGET_STICKY_RATIO: 0.85
};
